spring.application.name=spring-ecomm


//mySql
spring.datasource.username=root
spring.datasource.password=vaOVqJFvQnAhxXoVcTYgsyzeHBtwkNZs



spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:21462/railway

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql
spring.jpa.show-sql=true

spring.app.jwtSecret=G7H9K2L8P1Q5R3S6Tjijgegihehghwd3640V4W8X2Z1Y7A9B3
spring.app.jwtExpirationInSeconds=8640000


//adminProperties
app.admin.email=admin@gmail.com
app.admin.password=Admin@123
app.admin.enabled=true