spring.application.name=spring-ecomm


//mySql
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.url=jdbc:mysql://localhost:3307/ecomm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql
spring.jpa.show-sql=true

spring.app.jwtSecret=G7H9K2L8P1Q5R3S6Tjijgegihehghwd3640V4W8X2Z1Y7A9B3
spring.app.jwtExpirationInSeconds=864000

